#!/bin/bash

#########################################################################################################################
#
# first4 install script
#
# Version 	Date 		Changes				Author
# 0.1		2008-04-21	Initial Version			O. Procopio <orlando@procopio.ch>
#
#########################################################################################################################

function checkenv {
	QMAKE=`which qmake-qt4`
	INSTDIR=/usr/local/lib/first4
}

function setenv {
	
	echo 
	echo
	if [ "$QMAKE" = "" ]; 
	then 
		printf "Please enter the qmake (QT4) command: [$QMAKE] " 
		read QMAKE
	fi

	printf "Please enter the install directory: [$INSTDIR] " 
	read INSTDIR_TMP
	if [ "$INSTDIR_TMP" != "" ]
	then
		INSTDIR=$INSTDIR_TMP
	fi

	#Show env
	showenv

}

function showenv {

	echo
	echo
	echo "Please check if everything is correct:"
	echo "======================================"
	echo "Qmake command: $QMAKE"
	echo "Target directory: $INSTDIR"
	echo "======================================"
	echo 
	printf "Continue?: (y/n/q)"
	read CONT
	if [ "$CONT" = "n" ]
	then
	        setenv
	fi
	if [ "$CONT" = "q" ]
	then
	        echo "Exiting..."
		exit 0
	fi
	if [ "$CONT" = "y" ]
	then
	        install
	fi

}

function install {
	
	echo	
	echo "Create Makefile..."
	echo 
	${QMAKE}

	echo
	echo "Compiling..."
	echo
	make

	#check if I am root
	if [ `whoami` != "root" ]
	then
		echo 
		echo 
		echo "To create the install directory and install first4 you need root rights."
		echo "I will perform now a: sudo mkdir -p $INSTDIR ."
		echo "Please enter your or the root passwort."
		echo 
		echo "Create target directories..."
		sudo mkdir -p $INSTDIR/bin
		sudo mkdir -p $INSTDIR/translations
		echo "Copy files..."
		sudo cp bin/* $INSTDIR/bin/
		sudo cp resources/images/logo.png $INSTDIR/bin/logo.png
		sudo cp resources/translations/*.qm $INSTDIR/translations/
		sudo cp resources/first4.desktop /usr/share/applications/first4.desktop
	else
		echo "Create target directories..."
		mkdir -p $INSTDIR/bin
		mkdir -p $INSTDIR/translations
		echo "Copy files..."
		cp bin/* $INSTDIR/bin/
		cp resources/images/logo.png $INSTDIR/bin/logo.png
		cp resources/translations/*.qm $INSTDIR/translations/
		cp resources/first4.desktop /usr/share/applications/first4.desktop
	fi
	
	echo
	echo
	echo "Installation completed."
	echo "Thank you for choosing first4."
	echo "http://www.procopio.ch"
	echo
}

#Check env
checkenv

echo 
echo 
echo #################################################
echo #                                               #
echo #        Welcome to the first4 Installer        #
echo #                                               #
echo #################################################

#Set env
setenv

